version: '3'

services:
  cont_1:
    build:
      ./config
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - data_base

  data_base:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
